choco install awscli
choco install azure-cli
choco install cmder
choco install docker
choco install git
choco install googlechrome
choco install fiddler4
choco install linqpad5
choco install nodejs
choco install notepadplusplus
choco install office365business
choco install openvpn
choco install postman
choco install resharper
choco install slack
choco install Spotify
choco install terraform
choco install totalcommander
choco install vscode
choco install visualstudio2017professional
choco install yarn
