choco install awscli -y
choco install azure-cli -y
choco install cmder -y
choco install docker -y
choco install git -y
choco install googlechrome -y
choco install fiddler4 -y
choco install linqpad5 -y
choco install nodejs -y
choco install notepadplusplus -y
choco install office365business -y
choco install openvpn -y
choco install postman -y
choco install resharper -y
choco install slack -y
choco install Spotify -y
choco install terraform -y
choco install totalcommander -y
choco install vscode -y
choco install visualstudio2017professional -y
choco install yarn -y
